### ISSUE TITLE
alpha/beta diversity measures

### ISSUE THREAD

**Issue by abremges** [CAMI-challenge/OPAL#10]
From David's email, some of which to be implemented:

>I did find a nice summary of alpha/beta diversity metrics that are important to biologists (imported from the 16S realm):
https://www.drive5.com/usearch/manual/alpha_diversity.html
https://www.drive5.com/usearch/manual/alpha_metrics.html
https://www.drive5.com/usearch/manual/beta_diversity.html
https://www.drive5.com/usearch/manual/beta_metrics.html
>
>As well as a very nice math paper that shows how lots of these metrics are related to each other (and can be calculated in a straightforward way in a unified framework): https://www.dropbox.com/s/0nts9ypq5cyorv2/Leinster%202014%20Measuring%20diversity%20the%20importance%20of%20species%20similarity.pdf?dl=0
>
>Given another couple days or so, I'll be able to get a ranked list of important diversity metrics to include, and will look for implementations of them (unless one of you has already done this).

(As I found out the hard way, Bray Curtis is simply 1/2 our L1 Norm, thus we kind of have it already.)

**Comment by dkoslicki** [comment]
Way to visualize beta-diversity: scatter plot of (x,y) points. The x-values are the beta_diversity(tool k on sample i, tool k on sample j), y-values are the beta_diversity(gold standard sample i, gold standard sample j). Do this for all i and j. One scatter plot for each tool (indexed by k).

**Comment by fernandomeyer** [comment]
All metrics (but Faith's Phylogenetic Diversity, Chao1 / Chao2) have been implemented.
