### ISSUE TITLE
New multi-sample toy data set

### ISSUE THREAD

**Issue by abremges** [CAMI-challenge/OPAL#20]
For the second mode of Opal (cross-sample comparisons to check how well tools capture e.g. changes in alpha diversity), we need to simulate a small and controlled data set, generate the gold standard, and run different profilers on it.

@fernandomeyer and I will think about it and discuss the experimental setup (probably involving @AlphaSquad, too, if CAMISIM can do the job).

**Comment by fernandomeyer** [comment]
Cross-sample comparisons have been done using CAMI I high and CAMI II mouse gut data. Alpha/beta diversities can now be measured with Shannon, rarefaction curves...
