### ISSUE TITLE
Discrepancies in L1 norm between opal and CAMI

### ISSUE THREAD

**Issue by dkoslicki** [CAMI-challenge/OPAL#23]
Metrics in CAMI were computed with [this code](https://github.com/CAMI-challenge/bbx-profiling-evaluation-dk/blob/master/src/ProfilingMetrics.py). See lines 154-175 for the computation of L1 norm.

**Comment by fernandomeyer** [comment]
Already implemented:
-Abundances will be normalized by default for all metrics, as discussed.
-Multiple predictions for the same taxon will be summed up.
