### ISSUE TITLE
Error when running tsv2biom.py

### ISSUE THREAD

**Issue by muslih14** [CAMI-challenge/OPAL#24]
Thanks for the awesome script.

I've followed the installation and have been able to run OPAL but  I'm having an issue with the tsv2biom.py script.
When I run the example:
python3 tsv2biom.py data/cranky_wozniak_13 -o output_dir/cranky_wozniak_13.biom
I keep getting : "Input file could not be read" error

**Comment by sjanssen2** [comment]
As an alternative, I suggest 
 1. installing [miniconda](https://conda.io/miniconda.html)
 2. create an python3 conda environment
 3. install native "biom-format" and "h5py" conda packages to
finally call `biom convert --to-hdf5 -i input.tsv -o output.biom`

**Comment by muslih14** [comment]
My input file for biom convert is in the CAMI biobox format.  Will the biom output using biom convert work with Opal?

**Comment by fernandomeyer** [comment]
Fixed.
@muslih14 Thanks for reporting the error.
The output of `biom convert` does not work with OPAL.

**Comment by muslih14** [comment]
Thank you, fernando! I will give it a try right now. 
I hope you can indulge me this question : I'm looking to convert SuperFOCUS and FOCUS outputs to biom or the CAMI bioboxes format. Do you know of any tool that I could use?

**Comment by fernandomeyer** [comment]
@muslih14 There is a biobox (docker container) that automatically converts the output of FOCUS to the CAMI bioboxes format. See: https://github.com/CAMI-challenge/docker_profiling_tools/tree/master/focus

**Comment by muslih14** [comment]
Thank you, Fernando!
