### ISSUE TITLE
Strains in the gold standard?

### ISSUE THREAD

**Issue by luizirber** [CAMI-challenge/OPAL#30]
Hello,

I was looking at the [CAMI II MG gold standard](https://github.com/CAMI-challenge/OPAL/blob/36613fe52207c232c9af4d39ce8f53b565d8add3/data/gs_cami_ii_mg.profile) and noticed lines with `strains` (which is also listed in the `ranks`. Since the gold standard doesn't mention, what taxonomy was used? It seems to be NCBI-like or derived, but I thought [NCBI doesn't assign strain tax IDs](https://www.ncbi.nlm.nih.gov/pubmed/25197497/) since 2014?

```
547042	strain	2|976|200643|171549|815|816|387090|547042	Bacteria|Bacteroidetes|Bacteroidia|Bacteroidales|Bacteroidaceae|Bacteroides|Bacteroides coprophilus	0.0	4447072.1

```
`547042` is listed as `Rank: no rank` in the [NCBI Taxonomy](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=547042&lvl=3&lin=f&keep=1&srchmode=1&unlock)

Another example:
```
36874.1	strain	2|976|200643|171549|171551|836|36874|36874.1	Bacteria|Bacteroidetes|Bacteroidia|Bacteroidales|Porphyromonadaceae|Porphyromonas|Porphyromonas cangingivalis|Unclassified Porphyromonas cangingivalis strain	0.0	187028.0
```
`36874.1` is not a valid NCBI Tax ID, so how was it assigned?

**Comment by luizirber** [comment]
> ```
> 547042	strain	2|976|200643|171549|815|816|387090|547042	Bacteria|Bacteroidetes|Bacteroidia|Bacteroidales|Bacteroidaceae|Bacteroides|Bacteroides coprophilus	0.0	4447072.1
> ```
> 
> `547042` is listed as `Rank: no rank` in the [NCBI Taxonomy](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=547042&lvl=3&lin=f&keep=1&srchmode=1&unlock)

So for this one I implemented some logic to check for `no rank` and figure out if it is a strain, subspecies in [gather_to_opal.py][0], and can get this call properly now.

[0]: https://github.com/dib-lab/2019-12-12-sourmash_viz/blob/723a612e00c78f7ec93d3aa24e464833c59c6f46/src/gather_to_opal.py#L83L106

> ```
> 36874.1	strain	2|976|200643|171549|171551|836|36874|36874.1	Bacteria|Bacteroidetes|Bacteroidia|Bacteroidales|Porphyromonadaceae|Porphyromonas|Porphyromonas cangingivalis|Unclassified Porphyromonas cangingivalis strain	0.0	187028.0
> ```
> 
> `36874.1` is not a valid NCBI Tax ID, so how was it assigned?

But this case is still confusing, and I'm curious to how it was added to the gold standard =]

**Comment by fernandomeyer** [comment]
In the CAMI gold standards, the strain IDs just reflect how many strains there are for a certain species. For instance, if there are 5 strains of Escherichia coli, then their strain IDs will be 562.1, 562.2, 562.3, 562.4, and 562.5. Which strain gets a certain number is random and therefore it is impossible to assess relative abundance predictions at the strain level, but at least we can assess if the number of predictions is similar as in the gold standard. Since there doesn't seem to be a established way to define strain IDs, this is the best that we can do right not.
Anyway, OPAL just matches taxon IDs, and how they are defined is not really relevant for the tool itself.

**Comment by luizirber** [comment]
> In the CAMI gold standards, the strain IDs just reflect how many strains there are for a certain species. For instance, if there are 5 strains of Escherichia coli, then their strain IDs will be 562.1, 562.2, 562.3, 562.4, and 562.5. Which strain gets a certain number is random and therefore it is impossible to assess relative abundance predictions at the strain level, but at least we can assess if the number of predictions is similar as in the gold standard. Since there doesn't seem to be a established way to define strain IDs, this is the best that we can do right not.
> Anyway, OPAL just matches taxon IDs, and how they are defined is not really relevant for the tool itself.

I see, thanks! I will still keep the info I can get from levels below species in the NCBI taxonomy, but not worry about the specific taxon ID formatting (it will still be summarized properly for higher levels anyway).
