### ISSUE TITLE
Interactive ranking plots labeled incorrectly

### ISSUE THREAD

**Issue by dkoslicki** [CAMI-challenge/OPAL#32]
In local testing, I've noticed that while the ranking table is correct, the labels on the plots are incorrect. i.e. the values on the interactive plots are correct, but the names of the labels are not.

How to replicate:
1. Take your favorite set of profile results and gold standard
2. Set all ranking weights to 0 save for one metric with weight of 1
3. Sort the table by that metric
4. Observe the labels do not correspond to the rankings

**Comment by fernandomeyer** [comment]
Fixed with caf4c3cb359d106166dfc2af68b5edb749681573 -- will be in version 1.0.9.
