### ISSUE TITLE
Expose branch length function on CLI for EMDUnifrac

### ISSUE THREAD

**Issue by dkoslicki** [CAMI-challenge/OPAL#33]
Currently the branch length function is hard coded [here](https://github.com/CAMI-challenge/OPAL/blob/unifrac/src/utils/ProfilingTools.py#L32). Want to expose this as an option on the command line.

**Comment by dkoslicki** [comment]
Can close after merge to master pending coordination with @fernandomeyer after Friday meeting.
Will need to see if we should make this a CLI option for `opal.py` itself

**Comment by fernandomeyer** [comment]
Branch length CLI option added with commit e9d555e78b616e75341ee1c60ed27a9694829ddc.

**Comment by dkoslicki** [comment]
Great! Looks to be working well: closing
