### ISSUE TITLE
Add ability to not normalize when computing EMDUnifrac

### ISSUE THREAD

**Issue by dkoslicki** [CAMI-challenge/OPAL#34]
Will need to make a clone of [this block of code](https://github.com/CAMI-challenge/OPAL/blob/unifrac/src/utils/ProfilingTools.py#L377-L482), but strip out the normalization. 

Will also need to detect if normalization is on/off from CLI

**Comment by dkoslicki** [comment]
Note: for unweighted unifrac, this makes no difference whatsoever.
For weighted unifrac, a choice will need to be made to "add back" the missing mass somehow. Eg. gold standard sums to 1, but sample1 sums to 0.4, you can do weighted unifrac on these as is, but what do you do with the missing 0.6 mass? Treat it as sitting at the root node (i.e. unclassified?)

**Comment by dkoslicki** [comment]
Can close after merge to master pending coordination with @fernandomeyer after Friday meeting.

**Comment by fernandomeyer** [comment]
Normalization selection (on/off) is passed on to unifrac computation with commit e9d555e78b616e75341ee1c60ed27a9694829ddc.
