### ISSUE TITLE
Add tree visualizations

### ISSUE THREAD

**Issue by dkoslicki** [CAMI-challenge/OPAL#37]
DK: Using [this repo](https://github.com/dkoslicki/CAMIProfilingVisualization), generate all plots for all tools for all ranks and store in folder.
Then pass off to FM to integrate into HTML as new tab.

**Comment by fernandomeyer** [comment]
The code in the referred repo has dependencies that need clarification, as described in this [issue](https://github.com/dkoslicki/CAMIProfilingVisualization/issues/14).
