### ISSUE TITLE
Filtering done before calling `compute_metrics` so that all metrics get filtered profiles

### ISSUE THREAD

**Issue by dkoslicki** [CAMI-challenge/OPAL#39]
Currently filtering only done in binary metrics. After discussing with @fernandomeyer , it seems better to filter before calling `compute_metrics` so all metrics get the filtered versions

**Comment by fernandomeyer** [comment]
Now implemented in 4facfba901ee9ccaf0a73011d1ef1925ffca8a57 and 385d0615212dc63a2dfe002339d36d2ab27e0965 and currently in [dev](/CAMI-challenge/OPAL/tree/dev).

**Comment by dkoslicki** [comment]
@fernandomeyer What are your thoughts on merging `dev` into `master`? It would let us close this issue (and probably other issues as well).
