### ISSUE TITLE
Example command

### ISSUE THREAD

**Issue by ScaonE** [CAMI-challenge/OPAL#45]
Dear all,

I wanted to test this install of OPAL

```bash
conda create --name opal --yes;
conda activate opal;
conda install python=3.7 --yes;
~/miniconda3/envs/opal/bin/pip3 install cami-opal;
/home/fr_scaerw/miniconda3/envs/opal/bin/opal.py -v;
```

> opal.py 1.0.10

I did a test using the example command (with a few additional options) & test data found in the GitHub repo: 

```bash
python3 /home/fr_scaerw/miniconda3/envs/opal/bin/opal.py \
        --gold_standard_file data/goldstandard_low_1.bin \
        --output_dir Output/Test_cami_low_full_options \
        --plot_abundances \
        --labels "TIPP, Quikr, MP2.0, MetaPhyler, mOTU, CLARK, FOCUS" \
        --desc "Test_cami_low_full_options" \
        --ranks "superkingdom,species" \
        data/cranky_wozniak_13 \
        data/grave_wright_13 \
        data/furious_elion_13 \
        data/focused_archimedes_13 \
        data/evil_darwin_13 \
        data/agitated_blackwell_7 \
        data/jolly_pasteur_3 \
```

My question is the following:
What I am expected to find in the output directory?
When I browse the "results.html" file, the beta-diversity tab is empty, same thing for the rarefaction sub-tab under the Gold standard tab.
Is this expected or not? Is there a place were the expected result of the test command is stored, to compare againt?

**Comment by fernandomeyer** [comment]
The results that you get in the tabs are expected, as both the beta diversity figures and rarefaction curve require multiple samples, and the given example contains a single sample.

Beta diversity is plotted as Bray-Curtis distances between profiling predictions on pairs of samples (x axis) vs the gold standard profiles (y axis); see [OPAL paper](https://doi.org/10.1186/s13059-019-1646-y). The rarefaction curve shows the number of taxa at each rank for a given number >1 of samples.

As output, you should get results.html, all results in multiple tab-separated tables and in results.tsv in _tidy_ format, and figures in pdf and png formats. Unfortunately I haven't uploaded the output of this example, but there are lots of others linked on the first page.

Sorry for the late reply. I hope this helps.
