### ISSUE TITLE
Option -r RANKS seems to not do much (GOLDSTD requires strain)

### ISSUE THREAD

**Issue by 4less** [CAMI-challenge/OPAL#50]
I have noticed that if I pass a gold standard profile without strain level assignments opal crashes, as it requires strain level information at different points in the script. Change the ranks from phylum to species seems to have no effect at all. I just removed the strain requirement where ever necessary to get it to run (which is more of a hacky fix than a permanent solution).

Why wouldn't I have strain information in a gold standard profile?
I changed cami gold standard profiles to a different NCBI taxonomy version and thus had to drop the strain level as the tool I used for that requires legal ncbi taxids (which some strains do not have).

Ideal behaviour: If strain level is omitted in the -r RANKS option, do not require strain level information in the gold standard profile and also do not show strain level as an option in the dropdown in the html or in the plots.

**Comment by fernandomeyer** [comment]
Sorry, but I am unable to reproduce the problem. Would it be possible for you to share your profiles?

Option -r only allows to select the taxonomic ranks used to score and compute performance rankings, which are shown in the "Rankings" tab of the output HTML. Metrics are computed for all taxonomic ranks available both in the gold standard and assessed profiles independently of what ranks you select with this option.
