### ISSUE TITLE
How does OPAL compute unifrac?

### ISSUE THREAD

**Issue by c4-driod** [CAMI-challenge/OPAL#55]
Hello, sorry to bother.
I have read a lot about the code of OPAL.
However, it's still hard for me to find out how you compute the unifrac score between gold standard and sample.
May I know your formula of unifrac or something like this? 
Thanks a lot.

yours, c4-driod.

**Comment by fernandomeyer** [comment]
OPAL uses an implementation of the EMDUnifrac described in [McClelland, J., Koslicki, D. J. Math. Biol. 2018](https://doi.org/10.1007/s00285-018-1235-9). The code is by @dkoslicki.
Sorry for the late reply, but I hope this is still useful.
