### ISSUE TITLE
Bray-Curtis distance calculation

### ISSUE THREAD

**Issue by rpelicaen** [CAMI-challenge/OPAL#57]
Hi,

Refering to Meyer et al., 2019; I was wondering if there is a difference between the Bray-Curtis distance calculation in the context of **Abundance estimates** and **Beta diversity metrics** ?

Thank you,
Rudy

**Comment by fernandomeyer** [comment]
Hi, there is no difference, we just used it in different ways. In _Abundance estimates_, we computed it between a prediction and the gold standard, and, in _Beta diversity metrics_, we computed it between pairs of predictions and pairs of gold standards of different samples, and then displayed it graphically.
