### ISSUE TITLE
Issue with CAMI OPAL Integration into Galaxy Platform

### ISSUE THREAD

**Issue by Alby-Git** [CAMI-challenge/OPAL#59]
Hi CAMI OPAL Team,

I am currently involved in integrating CAMI OPAL into the Galaxy platform [(Pull Request)](https://github.com/galaxyproject/tools-iuc/pull/6096) and have encountered some issues.

We are using specific data sets, which can be found [here](https://github.com/CAMI-challenge/OPAL/tree/master/data). Specifically, we are using:

- `goldstandard_low_1.bin` as the Gold standard file
- `jolly_pasteur_3, agitated_blackwell_7, cranky_wozniak_13, focused_archimedes_13, furious_elion_13, grave_wright_13` as Input files

Despite following the protocols, I could not replicate the metrics from the [CAMI II MG results](https://cami-challenge.github.io/OPAL/cami_ii_mg/) using OPAL version 1.0.12. The specific issues encountered include receiving 'nan' values for:

- Weighted UniFrac (CAMI)
- Unweighted UniFrac (CAMI)
- Weighted UniFrac error
- Unweighted UniFrac error

Switching to version 1.0.9 resulted in valid values for these metrics. However, we are unable to generate plots for beta diversity in both versions (1.0.9 and 1.0.12).

I have attached screenshots depicting these issues.

![OPAL_output-1 0 9_beta_diversity](https://github.com/CAMI-challenge/OPAL/assets/128725036/266d98ff-d222-4ac5-b57c-7f09269061f9)
![OPAL_output-1 0 9_UniFrac](https://github.com/CAMI-challenge/OPAL/assets/128725036/76d148ad-5db9-436c-893b-2d0d7a34938e)
![OPAL_output-1 0 12_beta_diversity](https://github.com/CAMI-challenge/OPAL/assets/128725036/d8ae51b9-11b6-42e2-83c4-855cef4943df)
![OPAL_output-1 0 12_UniFrac](https://github.com/CAMI-challenge/OPAL/assets/128725036/31860384-2b42-40c0-905b-5dc5fd2b5b57)

Could you please provide any insights or recommendations on what might be causing these discrepancies?

Thank you very much for your time and support.

Best regards

**Comment by fernandomeyer** [comment]
Hi, this is likely caused by recent versions of pandas and numpy. Please try using numpy==1.24.2 and pandas==1.5.3.
It seems that installation with conda gets the wrong versions, but running `pip install cami-opal` in the environment gets the correct ones, as in requirements.txt.
I will eventually update OPAL to support the new versions, but for now please try with these.
